### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by celsowhite** [celsowhite/remi#2]
- [ ] Better install flow with autoprovision of database.
- [ ] Multi column rich text
- [ ] Figure out how to make singletons appear upon initial download.
- [ ] Ability to use cdn client in prod and client in dev for sanity.
- [ ] Use query posts hook.
- [ ] Styled radix select.
- [ ] Date field for blog posts
- [ ] Slider component with keen.
- [ ] Make it a github template so its easier to install.
- [ ] Basic modal with smooth rise animation.
- [ ] SanityVideo component with hook up to asset api.
- [ ] Horizontal rule and spacer fields.
